// Replays the user's real episode-9 session (Mushoku Tensei S3E9 "Lament")
// through the actual console/download-ui modules, so the output below is
// generated by the shipping code rather than hand-written.
// Timings are compressed; part counts, byte sizes, servers, KIDs, resolutions
// and filenames are taken verbatim from the real run.
// STOP_AT=mid   -> snapshot while video + Japanese audio are in flight
// STOP_AT=final -> snapshot after both dubs decrypt and subtitles land
import { addTrack, beginSession, endSession, trackProgress, trackState } from '../modules/module.download-ui';
import { block, cekTree, console_, tracksTree } from '../modules/module.console';
import { Padding } from '../modules/module.rich';

const STOP_AT = process.env.STOP_AT ?? 'final';
// ms per part; the real run averaged ~518ms/part (355 parts in 3:04)
const PACE = Number(process.env.PACE ?? 3);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

(async () => {
	console_.info('[S3E9] - Lament [[green]✓[/] Japanese, [green]✓[/] English]');
	console_.info('Majin stream available at [repr.number]11449[/] kbps (1080p+), automatically enabling Majin quality mode');

	console_.info('Getting decryption keys with [cyan]widevine[/]');
	console_.print(
		new Padding(
			cekTree('Widevine', 'AAAAgnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7', [
				{
					kid: '3b6d103909d433af859533df3c498a02',
					key: '096b823d308f57ec57827a7c8c1e9414',
					from: 'Local Vault',
					trackKid: true
				}
			]),
			[0, 5]
		)
	);

	console_.write('\u0000MARK\u0000\n');

	// ── one live view for the whole episode ────────────────────────────────
	beginSession([{ key: 'video', type: 'Video', label: '1920x1080 (11449KiB/s) | vod-gcp.crunchyrollcdn.com' }]);
	addTrack({ key: 'audio-jpn', type: 'Audio', label: '200kB/s | Japanese | vod-gcp.crunchyrollcdn.com' });

	const VT = 355;
	const AT = 356;
	for (let i = 1; i <= VT; i++) {
		trackProgress('video', { completed: i, total: VT, bytes: Math.round(i * 1_186_000) });
		if (i <= AT) trackProgress('audio-jpn', { completed: i, total: AT, bytes: Math.round(i * 94_400) });
		if (STOP_AT === 'mid' && i === 214) {
			await sleep(260);
			endSession();
			return;
		}
		await sleep(PACE);
	}
	trackState('video', 'Downloaded');
	trackState('audio-jpn', 'Downloaded');

	// English dub joins the same tree (video is reused, not re-downloaded)

	addTrack({ key: 'audio-eng', type: 'Audio', label: '200kB/s | English | vod-cf-ap-south-1.crunchyrollcdn.com' });
	for (let i = 1; i <= AT; i++) {
		trackProgress('audio-eng', { completed: i, total: AT, bytes: Math.round(i * 94_600) });
		await sleep(PACE);
	}
	trackState('audio-eng', 'Downloaded');

	// decryption now happens with the view still on screen
	trackState('video', 'Decrypting');
	await sleep(500);
	trackState('video', 'Decrypted');
	trackState('audio-jpn', 'Decrypting');
	await sleep(250);
	trackState('audio-jpn', 'Decrypted');
	trackState('audio-eng', 'Decrypting');
	await sleep(250);
	trackState('audio-eng', 'Decrypted');

	const subs = ['ASS | eng | English', 'ASS | eng | English (Signs)', 'VTT | eng | English (CC)'];
	for (const f of subs) {
		addTrack({ key: `sub-${f}`, type: 'Subtitle', label: f });
		trackState(`sub-${f}`, 'Downloaded');
		await sleep(120);
	}
	await sleep(300);
	endSession();

	console_.info('[green][MDNX] All stream downloads & decryption completed.[/]');
	console_.info('Subtitles: en, en, en (Total: [repr.number]3[/])');
	console_.info('Required fonts: Arial, Trebuchet MS, Times New Roman, Georgia (Total: [repr.number]4[/])');
	console_.print(
		new Padding('[green]C:\\Users\\Rishad\\Videos\\Mushoku.Tensei.Jobless.Reincarnation.S03E09.Lament.1080p.CR.WEB.DL.AAC2.0.H.264.S3NKU.mkv[/] [text2]done[/]', [1, 0, 1, 5])
	);
})();
